---
services:
  traefik:
    image: docker.io/library/traefik:v3.4.3
    container_name: traefik
    ports:
      - 80:80
      - 443:443
      # Ports for TURN server (nextcloud-aio)
      # - "3479:3479/udp"
      # - "5350:5350/tcp"
    volumes:
      - /run/docker.sock:/run/docker.sock:ro
      - ./config/:/etc/traefik/
      - ./certs/:/var/traefik/certs/:rw
      - traefik_logs:/var/log/traefik
    environment:
      - CF_DNS_API_TOKEN=${CF_DNS_API_TOKEN}
    networks:
      - proxy
      - crowd
      # - nextcloud-aio
    restart: unless-stopped

volumes:
  traefik_logs:

networks:
  proxy:
    external: true # <-- (Optional) Change this to false if you want to create a new network
  crowd:
    external: true
  # if use nextcloud-aio, uncomment the next line
  # nextcloud-aio:
  #   external: true
