http:
  middlewares:
    secureHeaders:
      headers:
        accessControlAllowMethods:
          - GET
          - OPTIONS
          - PUT
        accessControlMaxAge: 100
        hostsProxyHeaders:
          - "X-Forwarded-Host"
        referrerPolicy: "same-origin"
        sslRedirect: true
        stsSeconds: 31536000
        stsIncludeSubdomains: true
        stsPreload: true
        forceSTSHeader: true
        contentTypeNosniff: true
        browserXssFilter: true
        customFrameOptionsValue: SAMEORIGIN

    # Argentina + OCI
    ar-only:
      plugin:
        geoblock:
          allowedIPAddresses:
            - your.vps.ip # ang v4
          countries:
            - AR
          silentStartUp: true
          allowLocalRequests: true
          logLocalRequests: true
          logAllowedRequests: false
          logApiRequests: false
          api: "https://get.geojs.io/v1/ip/country/{ip}"
          apiTimeoutMs: 500
          cacheSize: 25
          forceMonthlyUpdate: true
          allowUnknownCountries: false
          unknownCountryApiResponse: "nil"

    crowdsec:
      plugin:
        bouncer:
          enabled: true
          logLevel: INFO
          updateIntervalSeconds: 15
          updateMaxFailure: 0
          defaultDecisionSeconds: 15
          httpTimeoutSeconds: 10
          crowdsecMode: stream
          crowdsecAppsecEnabled: true
          crowdsecAppsecHost: crowdsec:7422
          crowdsecAppsecFailureBlock: true
          crowdsecAppsecUnreachableBlock: true
          crowdsecLapiKey: CHANGE_THIS # Replace CrowdSec API key (docker exec crowdsec cscli bouncers add crowdsecBouncer)
          # crowdsecLapiKeyFile: /etc/traefik/cs-privateKey-foo
          crowdsecLapiHost: crowdsec:8080
          crowdsecLapiScheme: http
          forwardedHeadersTrustedIPs:
            - YOUR.IP/24 # Reverse Proxy IP address
          clientTrustedIPs:
            - YOUR.LOCAL.IP/24 # Internal LAN IP addresses

    secured:
      chain:
        middlewares:
          - crowdsec
          - secureHeaders

tls:
  options:
    default:
      minVersion: "VersionTLS12"
      sniStrict: true
