---
global:
  checkNewVersion: false
  sendAnonymousUsage: true

# --> (Optional) Change log level and format here
#     - level: [TRACE, DEBUG, INFO, WARN, ERROR, FATAL]
#log:
# level: DEBUG
# <--

# --> (Optional) Enable accesslog here
#accessLog:
# <--
api:
  dashboard: false
  insecure: false

# -- Change EntryPoints here
entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
    # <--
  websecure:
    address: :443
    http:
      #      middlewares:
      #       - "crowdsec@file"
      tls:
        options: default
# <--

# -- Configure your CertificateResolver here
certificatesResolvers:
  cloudflare:
    acme:
      tlsChallenge: {}
      email: mail@domain.com # <-- Change this to your email
      storage: /var/traefik/certs/cloudflare-acme.json
      caServer: "https://acme-v02.api.letsencrypt.org/directory"
      dnsChallenge:
        provider: cloudflare # <-- (Optional) Change this to your DNS provider
        delayBeforeCheck: 0
        resolvers:
          - "1.1.1.1:53"
          - "8.8.8.8:53"
# <--

log:
  level: "INFO"
# --> Log for crowdsec
accessLog:
  filePath: "/var/log/traefik/access.log"
# <--

# --> (Optional) Disable TLS Cert verification check
# serversTransport:
#   insecureSkipVerify: true
# <--

# --> Providers
providers:
  docker:
    exposedByDefault: false # <-- (Optional) Change this to true if you want to expose all services
    # Specify discovery network - This ensures correct name resolving and possible issues with containers, that are in multiple networks.
    # E.g. Database container in a separate network and a container in the frontend and database network.
    network:
      - proxy
  file:
    directory: /etc/traefik
    watch: true
experimental:
  plugins:
    geoblock:
      moduleName: "github.com/PascalMinder/geoblock"
      version: "v0.3.3"
    bouncer:
      moduleName: "github.com/maxlerebourg/crowdsec-bouncer-traefik-plugin"
      version: "v1.4.4"
# <--
